/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import modelo.JuegoPrincipal;
import modelo.ListaDeJuego;
import modelo.PanelResultados;
import modelo.PanerCrearCarton;

/**
 *
 * @author mathy
 */
public class Ventana extends javax.swing.JFrame {
    
    private JuegoPrincipal juego;
    private PanerCrearCarton carton;
    private PanelResultados resultados;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ventana.class.getName());

    public Ventana() {
        initComponents();
        juego = new JuegoPrincipal();
        carton = new PanerCrearCarton(juego);
        resultados = new PanelResultados();
        juego.aggLista((ListaDeJuego) resultados);
        centro.setLayout(new BorderLayout());
        centro.add(carton, BorderLayout.WEST);
        centro.add(resultados, BorderLayout.CENTER);
        centro.revalidate();
        centro.repaint();
        conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAuto = new javax.swing.JButton();
        btnMan = new javax.swing.JButton();
        btnRei = new javax.swing.JButton();
        txtNumManual = new javax.swing.JTextField();
        centro = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bingo");

        btnAuto.setText("Automatico");
        btnAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoActionPerformed(evt);
            }
        });

        btnMan.setText("Manual");
        btnMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManActionPerformed(evt);
            }
        });

        btnRei.setText("Reinicio");
        btnRei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiActionPerformed(evt);
            }
        });

        txtNumManual.setText("jTextField1");
        txtNumManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumManualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout centroLayout = new javax.swing.GroupLayout(centro);
        centro.setLayout(centroLayout);
        centroLayout.setHorizontalGroup(
            centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );
        centroLayout.setVerticalGroup(
            centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(centro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAuto)
                        .addGap(39, 39, 39)
                        .addComponent(btnMan)
                        .addGap(18, 18, 18)
                        .addComponent(btnRei))
                    .addComponent(txtNumManual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNumManual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(centro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAuto)
                    .addComponent(btnMan)
                    .addComponent(btnRei))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAutoActionPerformed

    private void btnManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManActionPerformed

    private void btnReiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReiActionPerformed

    private void txtNumManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumManualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumManualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ventana().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAuto;
    private javax.swing.JButton btnMan;
    private javax.swing.JButton btnRei;
    private javax.swing.JPanel centro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtNumManual;
    // End of variables declaration//GEN-END:variables

    private void conectar() {
        btnAuto.addActionListener(e -> juego.automatico());

        btnMan.addActionListener(e -> {
            try {
                int n = Integer.parseInt(txtNumManual.getText());
                juego.manual(n);
            } catch(Exception ex) {
                JOptionPane.showMessageDialog(this, "Número no válido");
            }
        });

        btnRei.addActionListener(e -> juego.reiniciarJuego());
    }
}
